packages = [
    # Some defaults
    "curl",
    "wget",
    "vim",
    "git",
    "tree",
    "tmux",

    # Security
    "gnupg",
    "pass",

    # Development prerequisites
    "gnumake",
    "cmake",
    "gcc",
    "man-pages",

    # Personal development
    "wezterm",
    "zeal",
    "tokei",
    "nixpkgs-review",

    # Personal choices
    "lf",
    "st",
    "yadm",

    # Rust coreutils
    "lsd",
    "bat",
    "ripgrep",
    "fd",
    "du-dust",

    # Fluff
    "neofetch",
    "cmatrix",
    "xdotool",
    "htop",
    "ksystemlog",
    "toipe",

    # Relaxing
    "ytfzf",
    "newsboat",
    "cider",
    "calibre",

    # Utilities for UX
    "xorg.xrandr",
    "arandr",

    # Utilities for CLI UX
    "fzf",
    "lazygit",
    "entr",
    "starship",
    "poppler_utils",
    "file",
    "mediainfo",
    "massren",
    "chafa",

    # Hardware debugging utilities
    "pciutils",
    "usbutils",
    "smartmontools",

    # Software debugging
    "xorg.xev",

    # Programming languages
    "python3",
    "cargo",
    "octave",

    # Formatters
    "nixfmt",
    "rustfmt",

    # Graphical defaults
    "zathura",
    "signal-desktop",
    "sxiv",
    "chromium",
    "maim",
    "pavucontrol",

    # Productivity
    "thunderbird",
    "obsidian",
    "texlive.combined.scheme-full",
    "pandoc",
    "anki",
    "unzip",
    "libreoffice",
    "mendeley",

    # CLI productivity
    "imagemagick",
    "ffmpeg",

    # Mathematics and other study-related program
    # "geogebra6",

    # Proprietary stuff
    # "discord",
]
