#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Use starship for prompt
eval "$(starship init bash)"

# Use neovim as editor
export VISUAL=nvim
export EDITOR="$VISUAL"

# Quit to current directory in nnn
export NNN_TMPFILE="/tmp/nnn"
n() {
        nnn "$@"

        if [ -f $NNN_TMPFILE ]; then
                . $NNN_TMPFILE
                rm -f $NNN_TMPFILE > /dev/null
        fi
}

# Set history preferences
export HISTSIZE=10000
export HISTFILESIZE=1000000
export HISTCONTROL=ignoredups # ignore duplicates happening right after one another
