[infiniterecursion.eu]
source   = maildir://~/Maildir/sybrand@infiniterecursion.eu
check-mail-cmd = offlineimap -a infiniterecursion
outgoing = smtp://sybrand%40infiniterecursion.eu@smtp.hostinger.com:587
outgoing-cred-cmd = "pass show mail/sybrand@infiniterecursion.eu"
default  = INBOX # TODO: Set up notmuch to show subset by default
from     = Sybrand Aarnoutse <sybrand@infiniterecursion.eu>

[neuralcoding.com]
source   = maildir://~/Maildir/sybrand@neuralcoding.com
check-mail-cmd = offlineimap -a neuralcoding
outgoing = smtps://sybrand%40neuralcoding.com@mx.sohosted.com:587
outgoing-cred-cmd = "pass show mail/sybrand@neuralcoding.com"
default  = INBOX # TODO: Set up notmuch to show subset by default
from     = Sybrand Aarnoutse <sybrand@neuralcoding.com>
