[infiniterecursion.eu]
source   = maildir://~/Maildir/sybrand@infiniterecursion.eu
outgoing = smtps://0.0.0.0:587
default  = INBOX
from     = Sybrand Aarnoutse <sybrand@infiniterecursion.eu>

[neuralcoding.com]
source   = maildir://~/Maildir/sybrand@neuralcoding.com
outgoing = smtp://sybrand%40neuralcoding.com@mx.sohosted.com:587
default  = INBOX
from     = Sybrand Aarnoutse <sybrand@neuralcoding.com>
