# Use same keyboard config in tty
console.useXkbConfig = true

# Add font capable of displaying 汉字
fonts.packages = [ "noto-fonts-cjk-sans" ]


# TODO: declaratively configure fcitx
# Disable default fcitx module
#disabledModules = [ "i18n/input-method/fcitx.nix" ];

[i18n.inputMethod]
enable = true
type = "fcitx5"
fcitx5.addons = [ "fcitx5-chinese-addons", "fcitx5-rime" ]

[services.xserver.xkb]
layout = "us"
