[nix]
# Use experimental flakes
extraOptions = """
  experimental-features = nix-command flakes
"""

# Save space
settings.auto-optimise-store = true

[nix.gc]
automatic = true
dates = "monthly"
options = "--delete-older-than 30d"
