[nix]
# Use experimental flakes
extraOptions = """
  experimental-features = nix-command flakes
"""

# Save space
settings.auto-optimise-store = true

# Pin NIX_PATH
nixPath = [ "nixpkgs=flake:nixpkgs", "nixos-config=/etc/nixos/configuration.nix" ]

[nix.gc]
automatic = true
dates = "monthly"
options = "--delete-older-than 30d"
