environment.systemPackages = [
    # Trying out / Experimental
    "btop",
    "hyperfine",
    "elinks",
    "piper-tts",
    "nix-tree",
    "racket",
    # "haskellPackages.hell", currently broken?
    "taskwarrior3",
    "taskwarrior-tui",
    "hledger",

    # Some defaults
    "curl",
    "wget",
    "nmap",
    "vim",
    "git",
    "tree",
    "tmux",

    # Security
    "gnupg",
    "pass",

    # Development prerequisites
    "gnumake",
    "cmake",
    "gcc",
    "man-pages",
    "glibcInfo", # man(3) C functions
    "gdb", # Debugging

    # Personal development
    "tokei",
    "nixpkgs-review",
    "sqlite",
    "rr", # Deterministic debugging (and reverse execution!)
    "nil", # Nix LSP
    "clang-tools", # C/C++ LSP
    "dhall-lsp-server", # Dhall LSP
    "binsider", # Inspect binaries

    # Lean
    "elan",
    "lean4",

    # Personal choices
    "lf",
    "st",
    "helix",

    # Rust coreutils
    "lsd",
    "bat",
    "ripgrep",
    "fd",
    "dua",
    "procs",
    "hyperfine",

    # Fluff
    "macchina",
    "cmatrix",
    "xdotool",
    "htop",
    "toipe",

    # Relaxing
    "ytfzf",
    "newsboat",
    "calibre",

    # Utilities for UX
    "xorg.xrandr",
    "arandr",
    "alsa-utils",

    # Utilities for CLI UX
    "fzf",
    "lazygit",
    "entr",
    "starship",
    "poppler_utils",
    "file",
    "mediainfo",
    "massren",
    "chafa",
    "xclip",
    "script-directory",

    # Debugging utilities
    "pciutils",
    "usbutils",
    "smartmontools",
    "nvme-cli",
    "ngrep",
    "linuxPackages.perf",
    "bcc",
    "xorg.xev",
    "wireshark",
    "tcpdump",

    # Programming languages
    "python3",
    "rustup", # Use stateful managing with `rustup` for Rust ¯\_(ツ)_/¯
    "octave",

    # WebAssembly
    "wasmtime", # runtime
    "wabt",
    "binaryen",

    # Formatters
    "nixfmt-classic",

    # Graphical defaults
    "zathura",
    "signal-desktop",
    "sxiv",
    "maim",
    "pavucontrol",

    # Productivity
    "thunderbird",
    "texlive.combined.scheme-medium",
    "pandoc",
    "unzip",
    "libreoffice",
    "kiwix",

    # CLI productivity
    "imagemagick",
    "ffmpeg",
    "exiftool",
    "jq",

    # Misc.
    # "geogebra6",
    # "kicad", # pcb design
    # "freecad", " 3d printing design

    # Proprietary stuff
    # "discord",
]
