environment.systemPackages = [
    # Trying out / Experimental
    "helix",
    "yazi",
    "btop",
    "diskonaut",
    "hyperfine",
    "glow",
    "zellij",

    # Some defaults
    "curl",
    "wget",
    "nmap",
    "vim",
    "git",
    "tree",
    "tmux",

    # Security
    "gnupg",
    "pass",

    # Development prerequisites
    "gnumake",
    "cmake",
    "gcc",
    "man-pages",

    # Personal development
    "wezterm",
    "zeal",
    "tokei",
    "nixpkgs-review",
    "jetbrains.rust-rover",

    # Personal choices
    "lf",
    "st",
    "yadm",

    # Rust coreutils
    "lsd",
    "bat",
    "ripgrep",
    "fd",
    "du-dust",
    "procs",
    "hyperfine",
    "bandwhich",

    # Fluff
    "macchina",
    "cmatrix",
    "xdotool",
    "htop",
    "ksystemlog",
    "toipe",

    # Relaxing
    "ytfzf",
    "newsboat",
    "calibre",

    # Utilities for UX
    "xorg.xrandr",
    "arandr",

    # Utilities for CLI UX
    "fzf",
    "lazygit",
    "entr",
    "starship",
    "poppler_utils",
    "file",
    "mediainfo",
    "massren",
    "chafa",

    # Hardware debugging utilities
    "pciutils",
    "usbutils",
    "smartmontools",

    # Software debugging
    "xorg.xev",

    # Programming languages
    "python3",
    "rustup", # Use stateful managing with `rustup` for Rust ¯\_(ツ)_/¯
    "octave",

    # WebAssembly
    "wasmtime", # runtime
    "wabt",
    "binaryen",

    # Formatters
    "nixfmt-classic",

    # Graphical defaults
    "zathura",
    "signal-desktop",
    "sxiv",
    "chromium",
    "maim",
    "pavucontrol",

    # Productivity
    "thunderbird",
    "texlive.combined.scheme-full",
    "pandoc",
    "anki",
    "unzip",
    "libreoffice",
    "mendeley",
    "kiwix",

    # CLI productivity
    "imagemagick",
    "ffmpeg",

    # Misc.
    # "geogebra6",
    # "kicad", # pcb design
    # "freecad", " 3d printing design

    # Proprietary stuff
    # "discord",
]
