[system.autoUpgrade]
enable = true
flake = "/etc/nixos"
flags = [
  # Update nixpkgs
  "--update-input",
  "nixpkgs",
  # Update blacklist
  "--update-input",
  "hosts",

  # print build logs
  "-L",
]
# Update every week on saturday
dates = "Sat 02:00"
