# TODO: declaratively configure fcitx
# Disable default fcitx module
#disabledModules = [ "i18n/input-method/fcitx.nix" ];

fonts.fonts = [ "noto-fonts-cjk" ]

services.xserver.layout = "us"

[i18n.inputMethod]
enabled = "fcitx5"
fcitx5.addons = [ "fcitx5-chinese-addons", "fcitx5-rime" ]
