[networking]
# Enables wireless support via NetworkManager.
networkmanager.enable = true

# Use StevenBlack's blocklist:
# https://github.com/StevenBlack/hosts
stevenBlackHosts.enable = true

# The global useDHCP flag is deprecated, therefore explicitly set to false here.
# Per-interface useDHCP will be mandatory in the future, so this generated config
# replicates the default behaviour.
useDHCP = false
#interfaces.wlp3s0.useDHCP = true

[services.openvpn.servers.radboud]
# TODO: Fix systemd captures stdin so inputting username/password is impossible
autoStart = false
config = '''
client
proto tcp
dev tun
ca /etc/ssl/certs/ca-bundle.crt
remote-cert-tls server
auth-user-pass
cipher AES-256-CBC
verify-x509-name openvpn.science.ru.nl name
auth SHA256
comp-lzo
verb 3
remote openvpn.science.ru.nl 443
'''
